import fs from "fs-extra"
import path from "node:path"
import {
  resolveRegistryRoot,
  type TyohnConfig,
  rewriteComponentSource,
  loadComponentsManifest,
  loadStylesManifest,
} from "./project.js"

export async function ensureUtils(root: string, config: TyohnConfig) {
  const registry = resolveRegistryRoot()
  const utilsRel = config.aliases.utils.replace(/^@\//, "")
  const dest = path.join(root, `${utilsRel}.ts`)
  if (await fs.pathExists(dest)) return dest
  await fs.ensureDir(path.dirname(dest))
  await fs.copy(path.join(registry, "lib/utils.ts"), dest)
  return dest
}

export async function ensureHook(
  root: string,
  config: TyohnConfig,
  name: string
) {
  const registry = resolveRegistryRoot()
  const hooksRel = config.aliases.hooks.replace(/^@\//, "")
  const dest = path.join(root, hooksRel, `${name}.ts`)
  if (await fs.pathExists(dest)) return dest
  const src = path.join(registry, "hooks", `${name}.ts`)
  if (!(await fs.pathExists(src))) return null
  await fs.ensureDir(path.dirname(dest))
  await fs.copy(src, dest)
  return dest
}

export async function installStyle(
  root: string,
  config: TyohnConfig,
  styleName: string
) {
  const registry = resolveRegistryRoot()
  const styles = await loadStylesManifest()
  const entry = styles.items.find((s) => s.name === styleName)
  if (!entry) {
    const available = styles.items.map((s) => s.name).join(", ")
    throw new Error(`Unknown style "${styleName}". Available: ${available}`)
  }

  const stylesDir = path.join(root, config.css.stylesDir)
  await fs.ensureDir(stylesDir)
  const destName = `style-${styleName}.css`
  const dest = path.join(stylesDir, destName)
  await fs.copy(path.join(registry, entry.file), dest)

  // Remove other style-*.css siblings? apply replaces active; keep files, swap import.
  await patchGlobalsForStyle(root, config, styleName, entry.scopeClass)
  return { dest, scopeClass: entry.scopeClass }
}

export async function installTheme(root: string, config: TyohnConfig) {
  const registry = resolveRegistryRoot()
  const globalsPath = path.join(root, config.css.globals)
  await fs.ensureDir(path.dirname(globalsPath))

  const theme = await fs.readFile(path.join(registry, "theme/theme.css"), "utf8")
  const styleName = config.style
  const scopeClass = `style-${styleName.replace(/-vars$/, "")}`
  // For mira-vars, scope is still .style-mira inside the file; use file basename scope
  const styles = await loadStylesManifest()
  const entry = styles.items.find((s) => s.name === styleName)
  const resolvedScope = entry?.scopeClass ?? scopeClass

  const banner = `/* Generated by tyohncn — external style mode */
@import "tailwindcss";
@import "../${config.css.stylesDir}/style-${styleName}.css";

`
  // If style path relative from globals differs, fix:
  const globalsDir = path.dirname(globalsPath)
  const styleAbs = path.join(root, config.css.stylesDir, `style-${styleName}.css`)
  const relStyle = path.relative(globalsDir, styleAbs).replaceAll("\\", "/")

  const content = `/* Generated by tyohncn — external style mode */
@import "tailwindcss";
@import "${relStyle.startsWith(".") ? relStyle : `./${relStyle}`}";

${theme}
`

  if (await fs.pathExists(globalsPath)) {
    const existing = await fs.readFile(globalsPath, "utf8")
    if (!existing.includes("Generated by tyohncn")) {
      // Merge carefully: prepend import if missing
      const importLine = `@import "${relStyle.startsWith(".") ? relStyle : `./${relStyle}`}";`
      let next = existing
      if (!next.includes(`style-${styleName}.css`)) {
        if (next.includes('@import "tailwindcss"')) {
          next = next.replace(
            '@import "tailwindcss";',
            `@import "tailwindcss";\n${importLine}`
          )
        } else {
          next = `${importLine}\n${next}`
        }
      }
      if (!next.includes("--primary:")) {
        next = `${next}\n\n${theme}`
      }
      await fs.writeFile(globalsPath, next)
      return globalsPath
    }
  }

  await fs.writeFile(globalsPath, content)
  // Ensure html/body can host scope class — documented in README; write a tiny helper note
  void banner
  void resolvedScope
  return globalsPath
}

async function patchGlobalsForStyle(
  root: string,
  config: TyohnConfig,
  styleName: string,
  _scopeClass: string
) {
  const globalsPath = path.join(root, config.css.globals)
  if (!(await fs.pathExists(globalsPath))) return

  let css = await fs.readFile(globalsPath, "utf8")
  const globalsDir = path.dirname(globalsPath)
  const styleAbs = path.join(root, config.css.stylesDir, `style-${styleName}.css`)
  const relStyle = path
    .relative(globalsDir, styleAbs)
    .replaceAll("\\", "/")
  const importPath = relStyle.startsWith(".") ? relStyle : `./${relStyle}`

  // Replace any existing style-*.css import from styles dir
  const styleImportRe =
    /@import\s+["']([^"']*style-[^"']+\.css)["']\s*;/g
  if (styleImportRe.test(css)) {
    css = css.replace(styleImportRe, `@import "${importPath}";`)
  } else if (css.includes('@import "tailwindcss"')) {
    css = css.replace(
      '@import "tailwindcss";',
      `@import "tailwindcss";\n@import "${importPath}";`
    )
  } else {
    css = `@import "${importPath}";\n${css}`
  }

  await fs.writeFile(globalsPath, css)
}

export async function installComponent(
  root: string,
  config: TyohnConfig,
  name: string,
  installed = new Set<string>()
): Promise<string[]> {
  if (installed.has(name)) return []
  installed.add(name)

  const registry = resolveRegistryRoot()
  const manifest = await loadComponentsManifest()
  const item = manifest.items.find((c) => c.name === name)
  if (!item) {
    throw new Error(
      `Unknown component "${name}". Run: tyohncn list components`
    )
  }

  const written: string[] = []

  for (const dep of item.registryDependencies) {
    written.push(...(await installComponent(root, config, dep, installed)))
  }

  if (item.file.includes("sidebar") || name === "sidebar") {
    await ensureHook(root, config, "use-mobile")
  }

  const src = path.join(registry, item.file)
  let source = rewriteComponentSource(await fs.readFile(src, "utf8"), config)
  // Resolve IconPlaceholder → selected icon library (shadcn-compatible)
  const { transformIconPlaceholders } = await import("./transform-icons.js")
  source = transformIconPlaceholders(source, config.iconLibrary)
  const uiRel = config.aliases.ui.replace(/^@\//, "")
  const dest = path.join(root, uiRel, `${name}.tsx`)
  await fs.ensureDir(path.dirname(dest))
  await fs.writeFile(dest, source)
  written.push(dest)

  // IMPORTANT: no transformStyleMap, no cn-* strip
  if (/\bcn-[a-z0-9-]+\b/.test(source) === false && name !== "aspect-ratio") {
    // aspect-ratio may be thin; others should keep hooks
  }

  return written
}

export function componentsKeepCnHooks(source: string): boolean {
  // Detect if any cn-* class remains (external mode invariant)
  return /["'`][^"'`]*\bcn-[a-z0-9-]+/.test(source)
}
